version: "3.8"

services:
  go:
    container_name: go
    image: go-development:latest
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    environment:
      - DBHOST=db
      - DBUSER=${DBUSER}
      - DBPASS=${DBPASS}
      - DBNAME=${DBNAME}
    depends_on:
      db:
        condition: service_healthy
    tty: true
  db:
    container_name: db
    image: mysql:8.2.0
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - .sql:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=${DBUSER}
      - MYSQL_PASSWORD=${DBPASS}
      - MYSQL_DATABASE=${DBNAME}
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u$DBUSER -p$DBPASS

volumes:
  db-data: