version: "3.8"

services:
  go:
    container_name: go
    image: go-development:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      # - DB_USER="${DBUSER}"
      # - DB_PASSWORD="${DBPASS}"
      # - DBUSER=test_user
      - DBHOST=db
      - DBUSER=test_user
      - DBPASS=test_password
      # - MYSQL_HOST=db
    # 完全に起動する前にgo側のコンテナが立ち上がることを防ぐ
    depends_on:
      - db
    # depends_on:
    #   db:
    #     condition: service_healthy
    tty: true
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    # entrypoint: [ "air", "-c", ".air.toml"]
    # command: ["./main"]
  db:
    container_name: db
    image: mysql:8.2.0
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - .sql:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=test_user
      - MYSQL_PASSWORD=test_password
      - MYSQL_DATABASE=myapp
    # healthcheck:
    #   test: mysqladmin ping -h 127.0.0.1 -u test_user -p test_password
      # test: mysqladmin ping -h 127.0.0.1 -u$$MYSQL_USER -p$$MYSQL_PASSWORD

volumes:
  db-data: